version: "3.9"

services:
  leasingninja:
    build: .
    image: ghcr.io/dqualizer/leasing-ninja:latest
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    ports:
      - 8080:8080