name: LeasingNinja Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build with Maven without tests
        run: >
          mvn --batch-mode --update-snapshots package -Dmaven.test.skip=true
      - name: Build with Maven without Jigsaw
        run: >
          bin/enable-jigsaw.sh disable
          mvn --batch-mode --update-snapshots package
          bin/enable-jigsaw.sh enable
